### ISSUE TITLE
Free space view

### ISSUE THREAD

**Issue by meloman27** [oviradoi/FsMega#12]
Thank you for this plugin! Please add free space view.

**Comment by oviradoi** [comment]
Currently, Total Commander does not allow file system plugins to display information about free space.

I'm afraid there is no way to show the free space in the Mega account similar to the way it's displayed for the local hard disks.

**Comment by meloman27** [comment]
Can this information be displayed in the connection log (where command CONNECT / LIST\)?

**Comment by oviradoi** [comment]
I suppose it would be possible.

I'm trying to implement it, but this will introduce a small delay when getting the used and total space.

I will implement a caching mechanism to only get this info after an upload or delete operation, or once every minute or so, in order not to have an annoying delay when navigating through folders.

**Comment by meloman27** [comment]
It will be just wonderful and convenient, a good idea!  Thank You!!!!

**Comment by oviradoi** [comment]
I have implemented this in the latest version, 1.6.0. Please let me know how it works for you.

**Comment by meloman27** [comment]
Wow! The new version works great and is very convenient! Thank you very much again!
