### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by huouer** [oviradoi/FsMega#2]
How to use the executable plugin already compiled? After installation and typing into the user name and password for Mega, I received "Login error". 

BTW, the Two-Factor Authentication is not enabled for my Mega account.

**Comment by oviradoi** [comment]
I'm sorry, I wasn't able to reproduce your problem. Logging in seems to work fine for me.

Please make sure that your email and password are correct, and that you can login to the website using the same username and password.

Alternatively, please let me know if your email and/or password contains any special characters (non-latin characters) so I can try to see if maybe my plugin does not handle those types of characters correctly.

**Comment by huouer** [comment]
Hi Ovidiu,
I updated my password to exclude any special characters. Interestingly, I
can make FsMega work on another computer. I just cannot make it work on my
office computer, which could be a group policy restriction?

Kind Regards

Ouer (Oliver) Hu, *PhD.*

+61 432 846 291 (M) <+61%20432%20846%20291>
+61 3 8838 9408 (H) <+61%203%209502%207422%20(H)>
***@***.*** ***@***.***>
4 Ripon Ct, Forest Hill, VIC 3131

**Comment by oviradoi** [comment]
If it works on a different computer, that means it's not a problem with special characters. I have tested it with latin characters, numbers and symbols, but I haven't tested it with chinese, japanese, korean characters.

It might be a problem with group policy, but it would be hard to identify such a problem.

I have one more idea: do you use a proxy server on the computer where you have this problem?

**Comment by oviradoi** [comment]
I have released a new version (1.1.0) that I have been working on for some time.

It uses a newer version of the Mega SDK, and it's able to save the login data using TC's master password. It will also autodetect the proxy settings if they are needed.

Please try it out and let me know if it fixes your problem.

If it does not, please download [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview), and run it while you try to log in. It will allow you to check the logs that the plugin writes during its operation. The logs that start with "FsMega" are the ones that come from the plugin.

If you post the logs here it might help to find the problem.

**Comment by huouer** [comment]
Agree. Ghisler's Cloud Plugin can successfully work in the same computer.
