### ISSUE TITLE
Using a fake proxy in Internet Explorer settings hangs Total Commander

### ISSUE THREAD

**Issue by Baltazar500** [oviradoi/FsMega#3]
When using a fake proxy (non-existent, for example 127.0.0.1:11111) in the Internet Explorer settings, the plugin hard hangs Total Commander when trying to connect. There are no reactions to the "Cancel" and "Pause" buttons. Hard freeze of the program.

<details>

![SNAGIT_2022 09 03_12 09 33_0009](https://user-images.githubusercontent.com/12525093/188251921-45bb5631-e2ce-47b0-bd20-60f47b241df0.jpg)

</details>

**Comment by oviradoi** [comment]
This was fixed in version 1.3.0.

The Mega SDK will retry the connection forever, but you will now be able to cancel the operation from TC.
