### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by guberm** [oviradoi/FsMega#6]
Getting an error at the login attempt.

The credentials are correct.

I have a 2FA for my login.

![image](https://user-images.githubusercontent.com/577099/193632761-73c1991d-3b69-4c66-a63b-2def6c42e0ae.png)

![image](https://user-images.githubusercontent.com/577099/193632611-c64828f7-0b65-4399-ac85-bcd809ed27fb.png)

**Comment by oviradoi** [comment]
Thanks for reporting this.

Unfortunately, the plugin does not support multi-factor login yet.

It's possible to implement, but I don't have MFA on my account so I could not test it.

**Comment by guberm** [comment]
Unfortunately, I'm not developing in C/C++, but I can assist you with the testing on my account

**Comment by oviradoi** [comment]
I have added support for multi-factor login in the latest version 1.4.0
